name: frauddetection
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - pip:
    - numpy==1.19.2
    - pandas==1.2.0 
    - matplotlib==3.3.3
    - jupyter==1.0.0
    - scikit-learn==0.23.2 
    - xgboost==1.3.1
    - catboost==0.24.4
    - scikit-optimize==0.8.1